### ISSUE TITLE
java.lang.NullPointerException when moving files

### ISSUE THREAD

**Issue by gprovenz** [gprovenz/geco-file-organizer#1]
java.lang.NullPointerException 
        at com.gprovenz.gecofileorg.reader.FileInfo.getInstance(FileInfo.java:89)
        at com.gprovenz.gecofileorg.actions.FileMover.moveFile(FileMover.java:56)
        at com.gprovenz.gecofileorg.actions.FileMover.lambda$moveAllFiles$1(FileMover.java:42)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEa

**Comment by gprovenz** [comment]
Fixed
